---
title: "first knit"
author: "Teresa Juan"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer 
I attended William Howard Taft High school up to eleventh grade, from there i went to Belmont Community Adult School where i graduated. During my time in High school i took Math and English, and i liked Math more then English. The reason why i dint like English was because it wasn't my first language so i struggled in the class more. However when i finished both classes i ended up getting a B in English and a C in Math.
  

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer 
I do have a computer at home and its a MacBook Pro, I actually got one to start this class. I don't consider my self an expert on computers, if i could rate my self i would give myself a 4. My internet at home is very stable and reliable. We all use the internet at home because my kids do school work, so far its fast.
  
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer 
Honestly i don't have any other name that i would prefer, just Teresa. However my closes friends do call me Teresita, or Resa.    
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
What I would like to achive in life for right now is to finish my two years of college, hoping to continue on to my next goal wich is to enroll in the RN program. Im not sure wich subject would be more interesting to me because I havent been in school for a while. Im hoping to like them all, i  like to learn new things even thought it takes me a wile to understand them. 
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
Ever since I came from Guatemala I haven't been to any other foreign country. If i have the opportunity to visit a foreign country in the future I would go to Honduras, France or Israel. I haven't been in the military, but if I was drafted I would chose the Marines. They have many carer opportunities available and at the same time they serve our country.
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
 






  




